# Generated by Django 5.0.1 on 2024-01-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsExtraction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='scheduled',
            field=models.DateTimeField(null=True),
        ),
    ]
