# Generated by Django 5.0.2 on 2024-02-28 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cas', '0003_cas_summary_current_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cas_document',
            name='password',
        ),
    ]
