# Generated by Django 5.0.2 on 2024-02-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cas', '0004_remove_cas_document_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cas_document',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
