name: Development

on:
  push:
    branches: dev
    
jobs:
  build:
    runs-on: vittae-game
    env:
      POETRY: /home/ubuntu/.local/bin/poetry
      DJANGO_SETTINGS_MODULE: webscrap.settings.dev
    defaults:
      run:
        working-directory: dev
    
    steps:
      - name: Clone repositories
        uses: actions/checkout@v4
        with:
          path: 'dev'

      - name: Installing Requirements
        run: $POETRY install --only main,server --sync

      - name: Checking Django Errors
        run: $POETRY run python manage.py check
          

      - name: Generating Django Migrations Files
        run: $POETRY run python manage.py makemigrations

      - name: Migrating Changes to Database
        run: $POETRY run python manage.py migrate


  deploy:
    runs-on: vittae-game
    needs: build
    steps:
      - name: Restart vittae-scrapping Service
        run: sudo systemctl restart vittae-scrapping-dev.service

      - name: Restart NGINX Server
        run: sudo service nginx restart
